/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeFooter: typeof import('./../components/homeFooter/index.vue')['default']
    HomeHeader: typeof import('./../components/homeHeader/index.vue')['default']
    IconCustomArrowBottom: typeof import('~icons/custom/arrow-bottom')['default']
    IconCustomArrowTop: typeof import('~icons/custom/arrow-top')['default']
    IconCustomCancel: typeof import('~icons/custom/cancel')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconCustomMenu: typeof import('~icons/custom/menu')['default']
    IconCustomTriangle: typeof import('~icons/custom/triangle')['default']
    LanguageSelector: typeof import('./../components/LanguageSelector/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
